package org.mendybot.common.application.model.media.tune.domain;

public enum NoteType
{
  NONE,
  WHOLE, HALF, QUARTER, EIGHTH, SIXTEENTH, THIRTYSECOND, SIXTYFOURTH, ONETWENTYEIGHTH,
  DOTTED_HALF, DOTTED_QUARTER, DOTTED_EIGHTH, DOTTED_SIXTEENTH, DOTTED_THIRTYSECOND, DOTTED_SIXTYFOURTH, 
  TRIPLET_SIXTEENTH, TRIPLET_EIGHTH,

}
